import type {
  Voyage,
  PortCard,
  ShipCard,
  Payment,
  Consult,
  AlertItem,
  DashboardStat,
  RegionStory,
  Review,
} from "./types";

export const reviews: Review[] = [
  {
    id: "rv1",
    author: "김**",
    title: "평생 잊지 못할 지중해 크루즈 여행",
    region: "서부지중해",
    ship: "Costa Smeralda",
    category: "유럽",
    content:
      "바르셀로나부터 로마까지, 매 순간이 감동이었습니다. 선상 서비스도 훌륭했고 기항지마다 새로운 감동을 받았습니다.",
    date: "2026-04-15",
    rating: 5,
    views: 234,
  },
  {
    id: "rv2",
    author: "이**",
    title: "빙하의 장관, 알래스카 크루즈",
    region: "알래스카",
    ship: "Royal Caribbean",
    category: "미주·알래스카",
    content:
      "글레이셔 베이의 빙하는 정말 장관이었습니다. 크루즈에서 보는 자연의 웅장함에 압도되었어요. 가족과 함께한 최고의 여행.",
    date: "2026-04-10",
    rating: 5,
    views: 189,
  },
  {
    id: "rv3",
    author: "박**",
    title: "두바이와 아부다비의 화려함",
    region: "아라비아해",
    ship: "MSC 월드유로파",
    category: "중동",
    content:
      "중동의 화려한 건축물과 문화를 경험할 수 있었습니다. 부르즈 칼리파, 셰이크 자이드 모스크 모두 인상적이었어요.",
    date: "2026-04-05",
    rating: 4,
    views: 156,
  },
  {
    id: "rv4",
    author: "최**",
    title: "부산에서 출발하는 편리한 크루즈",
    region: "동북아",
    ship: "MSC 벨리시마",
    category: "동북아",
    content:
      "부산 출발이라 공항 이동 부담이 없어서 너무 좋았습니다. 일본 기항지도 알차게 다녀왔어요.",
    date: "2026-03-28",
    rating: 5,
    views: 178,
  },
  {
    id: "rv5",
    author: "정**",
    title: "따뜻한 동남아 휴양 크루즈",
    region: "동남아",
    ship: "겐팅 드림",
    category: "동남아",
    content:
      "푸켓 해변이 정말 아름다웠습니다. 선상 수영장에서 여유롭게 쉬면서 힐링했어요.",
    date: "2026-03-20",
    rating: 4,
    views: 142,
  },
  {
    id: "rv7",
    author: "윤**",
    title: "천년의 항구, 동부지중해",
    region: "동부지중해",
    ship: "Costa Serena",
    category: "유럽",
    content:
      "그리스 산토리니의 노을은 평생 잊지 못할 거예요. 일정 내내 행복했습니다.",
    date: "2026-03-08",
    rating: 5,
    views: 167,
  },
  {
    id: "rv8",
    author: "한**",
    title: "잊지 못할 신혼 크루즈",
    region: "서부지중해",
    ship: "MSC Seaview",
    category: "유럽",
    content:
      "신혼여행으로 다녀왔는데 두 사람 모두 대만족이었습니다. 다음에 또 가고 싶어요.",
    date: "2026-02-28",
    rating: 5,
    views: 203,
  },
];

// ⚠️ 임시 목업 데이터 — 추후 DB(API) 연동으로 교체됩니다.

export const dashboardStats: DashboardStat[] = [
  { label: "이번 달 예약", value: "48", delta: "+12%" },
  { label: "확정 출발", value: "6", delta: "+2" },
  { label: "진행 중 상담", value: "23", delta: "-3" },
  { label: "이번 달 매출", value: "₩187M", delta: "+18%" },
];

export const regionStories: RegionStory[] = [
  {
    id: "r1",
    region: "미주·알래스카",
    watermark: "ALASKA",
    titleLines: ["알래스카,", "빙하와 숲 사이를 항해하다"],
    tags: ["시애틀과 밴쿠버에서 시작되는 대자연의 크루즈"],
    href: "#",
    imageUrl: "/regions/alaska.png",
  },
  {
    id: "r2",
    region: "유럽",
    watermark: "EUROPE",
    titleLines: ["유럽, 천년의", "항구 도시를 잇는 바다"],
    tags: ["서부지중해", "동부지중해", "북유럽을 품은 클래식 크루즈"],
    href: "#",
    imageUrl: "/regions/europe.png",
  },
  {
    id: "r3",
    region: "중동",
    watermark: "ARABIA",
    titleLines: ["아라비아해,", "사막과 도시의 럭셔리를 향해"],
    tags: ["두바이, 도하, 아부다비를 잇는 프리미엄 일정"],
    href: "#",
    imageUrl: "/regions/arabia.png",
  },
  {
    id: "r4",
    region: "동남아",
    watermark: "ASIA",
    titleLines: ["남국의 햇살을 품은", "리조트 크루즈"],
    tags: ["동남아", "싱가포르, 말레이시아, 태국을 잇는 여유로운 항해"],
    href: "#",
    imageUrl: "/regions/asia.png",
  },
  {
    id: "r5",
    region: "동북아",
    watermark: "EAST SEA",
    titleLines: ["부산에서 시작하는", "가까운 크루즈"],
    tags: ["일본, 중국, 대만을 잇는 편안한 동북아 일정"],
    href: "#",
    imageUrl: "/regions/busan.png",
  },
];

export const voyages: Voyage[] = [
  {
    id: "v1",
    title: "2026년 05월 14일 [로얄캐리비안 보이저호] 알래스카 크루즈 8박 10일",
    region: "미주·알래스카",
    shipName: "Voyager of the Seas",
    line: "Royal Caribbean",
    departDate: "2026-05-14",
    arriveDate: "2026-05-23",
    countries: ["미국", "캐나다"],
    itinerary: ["시애틀", "주노", "스캐그웨이", "케치칸", "빅토리아", "시애틀"],
    nights: 8,
    days: 10,
    priceFrom: 4290000,
    status: "예약 가능",
    dDay: 7,
    reservedCount: 26,
    passportDone: 20,
    passportPending: 6,
    contractCount: 23,
  },
  {
    id: "v2",
    title: "2026년 06월 16일 ☆발코니UP☆서부지중해 8박 11일 [Costa Smeralda]",
    region: "유럽",
    shipName: "Costa Smeralda",
    line: "Costa Cruises",
    departDate: "2026-06-16",
    arriveDate: "2026-06-26",
    countries: ["이탈리아", "프랑스", "스페인"],
    itinerary: ["로마", "제노아", "마르세유", "바르셀로나", "칼리아리", "나폴리", "로마"],
    nights: 8,
    days: 11,
    priceFrom: 5940000,
    status: "출발 확정",
    dDay: 40,
    reservedCount: 13,
    passportDone: 10,
    passportPending: 3,
    contractCount: 11,
  },
  {
    id: "v3",
    title: "2026년 07월 13일 동남아 크루즈 - Resort World [겐팅 드림 크루즈]",
    region: "동남아",
    shipName: "Genting Dream",
    line: "Resorts World Cruises",
    departDate: "2026-07-13",
    arriveDate: "2026-07-20",
    countries: ["싱가포르", "말레이시아", "태국"],
    itinerary: ["싱가포르", "페낭", "푸켓", "랑카위", "싱가포르"],
    nights: 7,
    days: 8,
    priceFrom: 2490000,
    status: "예약 가능",
    dDay: 67,
    reservedCount: 27,
    passportDone: 21,
    passportPending: 6,
    contractCount: 24,
  },
  {
    id: "v4",
    title: "부산출발 2026년 08월 16일 동북아크루즈 - MSC [벨리시마호]",
    region: "동북아",
    shipName: "MSC Bellissima",
    line: "MSC Cruises",
    departDate: "2026-08-16",
    arriveDate: "2026-08-21",
    countries: ["대한민국", "일본"],
    itinerary: ["부산", "후쿠오카", "나가사키", "부산"],
    dDay: 56,
    nights: 5,
    days: 6,
    priceFrom: 1890000,
    status: "출발 확정",
    reservedCount: 11,
    passportDone: 8,
    passportPending: 3,
    contractCount: 9,
  },
  {
    id: "v6",
    title: "2026년 12월 4일 아라비아해 크루즈 - [MSC월드유로파]",
    region: "중동",
    shipName: "MSC World Europa",
    line: "MSC Cruises",
    departDate: "2026-12-04",
    arriveDate: "2026-12-13",
    countries: ["아랍에미리트", "카타르"],
    itinerary: ["두바이", "아부다비", "도하", "두바이"],
    dDay: 166,
    nights: 9,
    days: 10,
    priceFrom: 4100000,
    status: "예약 가능",
    reservedCount: 22,
    passportDone: 17,
    passportPending: 5,
    contractCount: 19,
  },
];

export const portCards: PortCard[] = [
  {
    id: "p1",
    name: "바르셀로나",
    region: "유럽",
    country: "스페인",
    description: "가우디의 건축물과 지중해의 매력이 어우러진 도시",
    usedByCount: 12,
  },
  {
    id: "p2",
    name: "두바이",
    region: "중동",
    country: "아랍에미리트",
    description: "미래와 전통이 공존하는 사막의 도시",
    usedByCount: 8,
  },
];

export const shipCards: ShipCard[] = [
  {
    id: "s1",
    name: "MSC Seaview",
    line: "MSC 크루즈",
    capacity: 5179,
    description: "지중해를 누비는 대형 럭셔리 크루즈",
    usedByCount: 5,
  },
  {
    id: "s2",
    name: "Costa Serena",
    line: "코스타 크루즈",
    capacity: 3780,
    description: "이탈리아 감성의 클래식 크루즈",
    usedByCount: 4,
  },
];

export const payments: Payment[] = [
  {
    id: "pay1",
    customerName: "홍길동",
    voyageTitle: "유럽 지중해 - MSC Seaview",
    amount: 5940000,
    paid: 5940000,
    status: "결제완료",
    date: "2026-06-10",
  },
  {
    id: "pay2",
    customerName: "김미리",
    voyageTitle: "중동 - Costa Serena",
    amount: 4100000,
    paid: 1000000,
    status: "부분결제",
    date: "2026-06-12",
  },
];

export const consults: Consult[] = [
  {
    id: "c1",
    customerName: "이바다",
    phone: "010-1234-5678",
    topic: "알래스카 크루즈 객실 문의",
    status: "신규",
    createdAt: "2026-06-20",
  },
  {
    id: "c2",
    customerName: "박여행",
    phone: "010-2222-3333",
    topic: "동남아 크루즈 일정 변경",
    status: "진행 중",
    createdAt: "2026-06-19",
  },
];

export const alerts: AlertItem[] = [
  {
    id: "a1",
    level: "danger",
    tag: "D-150",
    message: "유럽 지중해 크루즈 - 여권 제출 기한 도래",
  },
  {
    id: "a2",
    level: "warning",
    tag: "D-120",
    message: "중동 크루즈 - 잔금 납부 안내 필요",
  },
  {
    id: "a3",
    level: "danger",
    tag: "여권 만료",
    message: "홍길동 고객 - 여권 만료 6개월 미만",
  },
  {
    id: "a4",
    level: "warning",
    tag: "미제출",
    message: "김미리 고객 - 여권 정보 미제출",
  },
];
